### ISSUE TITLE
Unable to launch LogicAssignmentTest.java as a JUnit test

### ISSUE THREAD

**Issue by ebumping** [mikebourgeois/CIS170Samples#2]
The import org.junit cannot be resolved.

Test cannot be resolved to a type

The method assertEquals(int, int) is undefined

etc. etc. every assert returns an error

**Comment by ebumping** [comment]
This leaves me unable to select run as JUnit Test under run config.

**Comment by mikebourgeois** [comment]
It should have had the junit jar already configured on the classpath, but it appears that it's not in the project zip file.  On Thursday I'll be getting everyone onto the project in GIT, which should help with this I think.

**Comment by ebumping** [comment]
Github is a great resource and we used it during my time doing analyst work.

**Comment by mikebourgeois** [comment]
Ya, I love it.  I used it extensively at my last job, and I don't think it'll add too much complexity for people?  Ok, if you add this to your .classpath file, it may fix you up.  <classpathentry kind="con" path="org.eclipse.jdt.junit.JUNIT_CONTAINER/4"/>

Alternatively, if you are familiar with GIT, you can try loading the project I have in this repo.  I need to work through the instructions on a system that doesn't have it yet, but I've started process here under the 'Getting the samples' section.  Feel free to give it a try.

https://github.com/mikebourgeois/CIS170Samples/wiki/1:-Getting-Started

**Comment by mikebourgeois** [comment]
Ugh, it stripped out the .classpath entry I referenced.  Check out the junit entry in this file for a reference if you are interested.  https://github.com/mikebourgeois/CIS170Samples/blob/master/CIS170Samples/.classpath

**Comment by ebumping** [comment]
So how would I use this most recent link as a reference?  Or has the
original file since been updated?  I was able to load from the repo but I
am not sure about proceeding with the .classpath reference mentioned in
this second email.

Thanks.

**Comment by ebumping** [comment]
(perhaps successful IRC server connection can be first criteria but I aim
to accomplish all of the following)
 * welcome followers
 * chat moderation
 * AI response
 * track time
 * rewards

**Comment by ebumping** [comment]
Mike,
My final project is coming along well but I was wondering if I could
refocus a couple acceptance criteria now that I have a better understanding
of the program I am writing and the twitch API.

Potential second draft of acceptance criteria...

-successful connection to the internet relay connection server
-chat moderation
-welcome viewers(I already have follower notifications so the bot being
involved is a little over the top and spammy in implementation)
-create a user list(this will serve as a basis for the currency game,
however the game inside the bot is an ambitious undertaking with multiple
components for me to work on)
-track time

Let me know what you think about these revised acceptance criteria.

Thanks!
-Dylan

**Comment by mikebourgeois** [comment]
Looks great to me Dylan, nice work!
Mike

**Comment by ebumping** [comment]
So I found out there were two conditions getting in the way of chat
moderation.

The first one being that, like I expected, moderators are unable to timeout
Broadcasters in their own channel.

The second being when Dom typed "get a haircut" the bot was iterating over
the list looking for the entire phrase within the list rather than just the
words in the user message.

Thank you for your time as an instructor and I look forward to having you
again next semester.

I am unable to find the course review link and if you would like to provide
me with that I would be glad to fill it out for you!

Thank you for your time and effort!
-Dylan

**Comment by ebumping** [comment]
Hi Mike,
We still have class today? it's still snowing here in NH but I'm not sure
how it is in ME.

Just wanted to confirm we still had class.

Thanks!
-Dylan

**Comment by mikebourgeois** [comment]
Hey Dylan!  Unless the school cancels, I plan on going.  With that said, I'll understand if you can't make it.  It is still snowing here now.
