### ISSUE TITLE
Setting up our own JUnit Test

### ISSUE THREAD

**Issue by ebumping** [mikebourgeois/CIS170Samples#4]
How would we go about creating our own JUnit test to test conditions of our hangman project?  Does anybody know?  Should we just work within the class folder for this?

**Comment by mikebourgeois** [comment]
Right click the project and select new JUnit Test.  If you put it in the same package as the class you are testing, you won't need to import the class you are testing.  Alternatively, check out the imports and @Test annotation on one of my tests, you can do the same in your own class.
