### ISSUE TITLE
Looping over an array

### ISSUE THREAD

**Issue by ebumping** [mikebourgeois/CIS170Samples#5]
Looping over an array of hints prints something like 

hang.Hints@15db9742
hang.Hints@6d06d69c
hang.Hints@7852e922

How do I make this into displaying an exact translation again?

**Comment by ebumping** [comment]
I think this has to do with overwriting a toString if anyone can confirm or deny?

**Comment by mikebourgeois** [comment]
That's right, if you override toString(), you can simply pass the object to sysout, and see anything you want, so long as you put it in the string that toString returns.

**Comment by ebumping** [comment]
Thanks! Figured it out.
